@extends('components.website.agency.layout.app')

@section('title', __('AI Performance Summary'))

@section('main')
<div class="container-fluid mt-4">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h4 class="mb-0"><i class="ph-sparkle text-primary"></i> AI Performance Summary</h4>
        <form method="POST" action="{{ route('agency.ai.summary.generate') }}">
            @csrf
            <button type="submit" class="btn btn-sm btn-outline-primary">
                <i class="ph-arrows-clockwise"></i> Regenerate
            </button>
        </form>
    </div>

    @if(session('success'))
        <div class="alert alert-success">{{ session('success') }}</div>
    @endif

    <div class="card shadow-sm">
        <div class="card-body">
            @if($summary)
                <p class="mb-0" style="line-height: 1.8; font-size: 15px;">{{ $summary }}</p>
            @else
                <p class="text-muted mb-0">No summary could be generated right now. Please try again shortly.</p>
            @endif
        </div>
    </div>

    <p class="text-muted small mt-3">
        This summary is generated by AI from your current dashboard KPIs and refreshes automatically every 12 hours,
        or on demand via the Regenerate button.
    </p>

    <hr class="my-4">

    <h6 class="fw-semibold mb-3">More AI Tools</h6>
    <div class="row g-3">
        <div class="col-md-6">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h6 class="fw-semibold mb-1"><i class="ph-clock-countdown"></i> Visa Delay Forecast</h6>
                    <p class="text-muted small mb-3">See which in-progress visa cases are at risk of running late, and their estimated completion date.</p>
                    <a href="{{ route('agency.ai.visa-delay-forecast') }}" class="btn btn-sm btn-outline-primary">Open Forecast</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h6 class="fw-semibold mb-1"><i class="ph-magic-wand"></i> Candidate Matcher</h6>
                    <p class="text-muted small mb-3">Open any of your jobs and use "Suggest Candidates" to rank your talent pool against that role.</p>
                    <a href="{{ route('agency.myjob') }}" class="btn btn-sm btn-outline-primary">Go to My Jobs</a>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection
